# Generated by Django 3.2.8 on 2021-10-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo1', models.ImageField(null=True, upload_to='images/')),
                ('photo2', models.ImageField(null=True, upload_to='images/')),
                ('photo3', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
