# Generated by Django 3.2.8 on 2021-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='category3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
