# Generated by Django 3.2.8 on 2021-10-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211018_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.CharField(choices=[('dft', 'Draft'), ('sub', 'Submitted'), ('pub', 'Published'), ('rej', 'Rejected')], default='dft', max_length=3),
        ),
    ]
