# Generated by Django 3.2.8 on 2021-10-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211019_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
