# Generated by Django 3.2.8 on 2021-10-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211019_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
