# Generated by Django 3.2.8 on 2021-10-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20211019_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='levels',
            field=models.CharField(choices=[('pub', 'Public User'), ('ath', 'Authenticated User'), ('adm', 'Administrator')], default='pub', max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='category1',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
