# Generated by Django 3.2.8 on 2021-10-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20211020_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AlterField(
            model_name='user',
            name='levels',
            field=models.CharField(choices=[('pubs', 'Public User'), ('auth', 'Authenticated User'), ('admn', 'Administrator')], default='pubs', max_length=4),
        ),
    ]
