# Generated by Django 3.2.8 on 2021-10-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category1',
            field=models.CharField(blank=True, choices=[('cur', 'Current Events'), ('con', 'Conspiracies'), ('nrg', 'Energy and Tech'), ('non', 'None')], default='non', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category2',
            field=models.CharField(blank=True, choices=[('cur', 'Current Events'), ('con', 'Conspiracies'), ('nrg', 'Energy and Tech'), ('non', 'None')], default='non', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category3',
            field=models.CharField(blank=True, choices=[('cur', 'Current Events'), ('con', 'Conspiracies'), ('nrg', 'Energy and Tech'), ('non', 'None')], default='non', max_length=3, null=True),
        ),
    ]
